### ISSUE TITLE
Not compatible with Python 3

### ISSUE THREAD

**Issue by travis-c-lagrone** [tkrajina/git-plus#15]

**Comment by serdardalgic** [comment]
Any plans on making git-plus python3 compatible?

**Comment by tkrajina** [comment]
Yes, I plan to, but I have no tome for this now. Pull requests are welcome.

**Comment by robgha01** [comment]
What is the status on this ?

**Comment by tkrajina** [comment]
> What is the status on this ?

Status: "Pull requests are welcome"
