### ISSUE TITLE
Option to exclude subdir

### ISSUE THREAD

**Issue by xoxys** [tkrajina/git-plus#18]
Sometimes it would be handy to have an option to temp or permanently exclude a subdir. Currently, I have to move out the subdir to achieve. Thanks for your work!

**Comment by tkrajina** [comment]
There is already a way to do that with git-multi. Search for `.multigit_ignore` in the README.

**Comment by xoxys** [comment]
Ok missed that line, thanks. That will solve the "permanent" exclude. What do you think about a cli flag for quick temp excludes? Something like `git-multi -x repo-to-exclude`?

**Comment by xoxys** [comment]
I had a quick look. Should be really straight forward to parse cli flag and add it to `ignore_projects`. I could look into that and create a PR if you like.

**Comment by tkrajina** [comment]
Oh, well, looks like I already added a flag in https://github.com/tkrajina/git-plus/blob/master/git-multi#L129 but then who-knows-what happened and I forgot to implement it :) You can just reuse that for the PR.

**Comment by xoxys** [comment]
Here you go :) happy to get your feedback

**Comment by xoxys** [comment]
@tkrajina Don't wanna to open a new issue, but could you tag a new release for an easy upgrade? Thanks again

**Comment by tkrajina** [comment]
@xoxys OK, here it is: `v0.4.4` (including a new version published on pypi).
