### ISSUE TITLE
Optional output of all versions in git semver

### ISSUE THREAD

**Issue by xoxys** [tkrajina/git-plus#21]
Hi, what do you think about an optional `--list` or `--list-all` flag to out put all old tags https://github.com/tkrajina/git-plus/blob/master/gitplus/cmd_git_semver.py#L45-L52

Always list all versions makes the output a bit messy and hard to read if there are a lot of tags. I can also prepare a PR if you are open to such changes.

**Comment by xoxys** [comment]
@tkrajina Any thoughts?

**Comment by tkrajina** [comment]
Just a moment, your suggestion is to change the default output of `git semver` to list only a part of versions and then `--list-all` to list them all?

If yes -- I'd rather prefer not to change the default output, but add `-n <number>` for the last version tags.

**Comment by xoxys** [comment]
What Im looking for is a way to shorten the output of `git semver`. Right now it looks like this:

```
❯ git semver --patch
 * v0.1.0
 * v0.1.1
 * v0.1.2
 * v0.1.3
 * v0.1.4
 * v0.1.5
 * v0.1.6
 * v0.1.7
 * v0.1.8
 * v0.1.9
 * v0.1.10
 * v0.1.11
 * v0.1.12
 * v0.1.13
 * v0.1.14
New minor: 0.2
 * v0.2.0
 * v0.2.1
 * v0.2.2
New minor: 0.3
 * v0.3.0
 * v0.3.1
New minor: 0.4
 * v0.4.0
New minor: 0.5
 * v0.5.0
New minor: 0.6
 * v0.6.0
New minor: 0.7
 * v0.7.0
 * v0.7.1
 * v0.7.2
 * v0.7.3
New minor: 0.8
 * v0.8.0
 * v0.8.1
 * v0.8.2
 * v0.8.3
 * v0.8.4
 * v0.8.5
 * v0.8.6
New minor: 0.9
 * v0.9.0
 * v0.9.1
 * v0.9.2
 * v0.9.3
 * v0.9.4
 * v0.9.5
New minor: 0.10
 * v0.10.0
 * v0.10.1
New minor: 0.11
 * v0.11.0
 * v0.11.1
New minor: 0.12
 * v0.12.0
New minor: 0.13
 * v0.13.0
 * v0.13.1
 * v0.13.2
 * v0.13.3
 * v0.13.4
 * v0.13.5
New minor: 0.14
 * v0.14.0
 * v0.14.1
New minor: 0.15
 * v0.15.0
New minor: 0.16
 * v0.16.0
 * v0.16.1
 * v0.16.2
 * v0.16.3
 * v0.16.4
 * v0.16.5
 * v0.16.6
New minor: 0.17
 * v0.17.0
 * v0.17.1
 * v0.17.2
 * v0.17.3
New minor: 0.18
 * v0.18.0
 * v0.18.1
 * v0.18.2
 * v0.18.3
New minor: 0.19
 * v0.19.0
 * v0.19.1
 * v0.19.2
 * v0.19.3
 * v0.19.4
New minor: 0.20
 * v0.20.0
 * v0.20.1
New minor: 0.21
 * v0.21.0
 * v0.21.1
 * v0.21.2
New minor: 0.22
 * v0.22.0
 * v0.22.1
 * v0.22.2
New minor: 0.23
 * v0.23.0
New minor: 0.24
 * v0.24.0
 * v0.24.1
New minor: 0.25
 * v0.25.0
 * v0.25.1
 * v0.25.2
New minor: 0.26
 * v0.26.0
 * v0.26.1
 * v0.26.2
 * v0.26.3
New minor: 0.27
 * v0.27.0

Last version: v0.27.0

Creating new version/tag: v0.27.1

Tag v0.27.1 created, you can push it now
```

What I want it to look like is:

```
❯ git semver --patch
Last version: v0.27.0

Creating new version/tag: v0.27.1

Tag v0.27.1 created, you can push it now
```

I don't have a strong opinion on how this can be achieved. `git semver --patch -n 0` or `git semver --patch --last-only` works for me as well.

**Comment by tkrajina** [comment]
ah, OK, I thought that you want to change the output of `git semver` (where it lists everything). You want to change only the output of one of the subcommands which *create* new version tags.

Yes, that makes sense to me. Feel free to make a PR which removes the listing in cases when a new version tag is created.

**Comment by tkrajina** [comment]
I pushed a new master now. It will output all the version tags only with `git semver`. If a new version is created -- not list is outputed.
