### ISSUE TITLE
Make a release.

### ISSUE THREAD

**Issue by a1russell** [tkrajina/git-plus#3]
I'd like to make git-plus installable via Homebrew and have already created a [git-plus pull request in the head-only tap](https://github.com/Homebrew/homebrew-head-only/pull/103). Making a release (maybe 0.1.0 to follow [semantic versioning](http://semver.org/)) would allow creation of a true Homebrew formula.

**Comment by tkrajina** [comment]
By "making a release" I suppose you mean adding a tag like "0.1.0", right?

**Comment by a1russell** [comment]
Not quite. It's the archive file I need. Read https://help.github.com/articles/creating-releases/

**Comment by tkrajina** [comment]
OK, thanks. 

I never used github releases page (I usually do releases for python profjects on pypi). 

Anyway, here it is: https://github.com/tkrajina/git-plus/releases .

**Comment by a1russell** [comment]
Thanks! Pull request created: https://github.com/Homebrew/homebrew/pull/37985

If would rather release on PyPI rather than GitHub, I can change the formula. Either way works.
