### ISSUE TITLE
How to colorise console output? 

### ISSUE THREAD

**Issue by siliconsenthil** [tkrajina/git-plus#4]
It would be really great to colorise the different child directories to make it pleasant to eye? Any ideas?

**Comment by tkrajina** [comment]
Hi @siliconsenthil 

Yeah, I like colored things, too ;) But I'm not good at selecting the right colors and targets, so a more specific suggestion on how/what to colorize is welcome.

**Comment by siliconsenthil** [comment]
We can show all the directories in some color (say green). That should be a good starting point. 

For diff and all other commands, we can use the same colors git uses.
