### ISSUE TITLE
Make a new release and add brew install in the docs

### ISSUE THREAD

**Issue by stevemao** [tkrajina/git-plus#5]

**Comment by tkrajina** [comment]
Hi @stevemao

I just added a release: https://github.com/tkrajina/git-plus/releases/tag/v0.2.0 but I'm not sure where/how to add those brew install docs? I think that brew install docs should be part of the brew formula for git-plus, not this repository.

**Comment by stevemao** [comment]
Yeah the brew install docs is added. But I think in order to install the latest version by brew, you need to bump the formula there...

**Comment by tkrajina** [comment]
Sorry, but at the moment I really have no time to figure out how/where I need (pull request to) to change the version and make sure everything works with it. If you can do it it's fine, otherwise this will have to wait a couple of weeks.
